"""Send outreach emails — gated, rate-limited, from the user's own mailbox.

Safety model (VISION.md §7):
  - Sends from the user's authenticated mailbox (Gmail API or SMTP), never a relay.
  - Default is DRY-RUN (logs what would be sent, sends nothing).
  - Real send requires BOTH settings.autopilot_outreach=true AND send=True.
  - Daily rate cap (settings.max_outreach_per_day) enforced via a send log.
  - Suppression list (data/outreach_suppression.txt) for opt-outs.
  - Resume PDF is ALWAYS attached when available.
  - LinkedIn + GitHub links are included in the email body.

This is low-volume, individually personalized outreach — not a blast tool.
"""
from __future__ import annotations

import smtplib
from dataclasses import dataclass
from datetime import date, datetime
from email.mime.application import MIMEApplication
from email.mime.multipart import MIMEMultipart
from email.mime.text import MIMEText
from pathlib import Path

from piperline.config import DATA_DIR, Settings


@dataclass
class SendResult:
    to: str
    subject: str
    sent: bool
    dry_run: bool = False
    blocked_reason: str | None = None
    error: str | None = None


_SEND_LOG = DATA_DIR / "outreach_send_log.txt"
_SUPPRESSION = DATA_DIR / "outreach_suppression.txt"


def _load_suppression() -> set[str]:
    if not _SUPPRESSION.exists():
        return set()
    return {line.strip().lower() for line in _SUPPRESSION.read_text().split("\n") if line.strip()}


def _count_sent_today() -> int:
    if not _SEND_LOG.exists():
        return 0
    today = date.today().isoformat()
    return sum(1 for line in _SEND_LOG.read_text().split("\n") if line.startswith(today))


def _log_send(to: str) -> None:
    _SEND_LOG.parent.mkdir(parents=True, exist_ok=True)
    with _SEND_LOG.open("a", encoding="utf-8") as f:
        f.write(f"{datetime.now().isoformat()} {to}\n")


def send_email(
    to: str,
    subject: str,
    body: str,
    *,
    settings: Settings,
    send: bool = False,
    resume_path: str | Path | None = None,
    linkedin_url: str | None = None,
    github_url: str | None = None,
) -> SendResult:
    """Send one outreach email with resume attached, or dry-run log it.

    Real send needs BOTH send=True AND settings.autopilot_outreach=true, plus
    passing the rate cap and suppression checks.

    resume_path: path to the PDF resume to attach (generated by the pipeline).
    linkedin_url: candidate's LinkedIn profile URL to include in the email.
    github_url: candidate's GitHub profile URL to include in the email.
    """
    to_lower = to.lower().strip()
    suppressed = _load_suppression()
    if to_lower in suppressed:
        return SendResult(to, subject, sent=False, blocked_reason="suppression list")

    sent_today = _count_sent_today()
    if sent_today >= settings.max_outreach_per_day:
        return SendResult(to, subject, sent=False,
                          blocked_reason=f"daily cap ({settings.max_outreach_per_day})")

    may_send = send and settings.autopilot_outreach
    if not may_send:
        return SendResult(to, subject, sent=False, dry_run=True)

    # Real send via SMTP with resume attachment.
    try:
        _send_smtp(to, subject, body, settings,
                   resume_path=resume_path,
                   linkedin_url=linkedin_url,
                   github_url=github_url)
        _log_send(to)
        return SendResult(to, subject, sent=True)
    except Exception as e:
        return SendResult(to, subject, sent=False, error=f"{type(e).__name__}: {e}")


def _send_smtp(
    to: str,
    subject: str,
    body: str,
    settings: Settings,
    *,
    resume_path: str | Path | None = None,
    linkedin_url: str | None = None,
    github_url: str | None = None,
) -> None:
    """Send via SMTP with optional resume attachment and profile links."""
    if not all([settings.smtp_host, settings.smtp_user, settings.smtp_pass]):
        raise NotImplementedError(
            "SMTP sending needs SMTP_HOST/SMTP_PORT/SMTP_USER/SMTP_PASS in config/.env. "
            "See config/.env.example. Gmail users: use an app password."
        )

    # Build the email body with profile links appended
    full_body = body
    if linkedin_url or github_url:
        links_section = "\n\n---\n"
        if linkedin_url:
            links_section += f"LinkedIn: {linkedin_url}\n"
        if github_url:
            links_section += f"GitHub: {github_url}\n"
        full_body = body + links_section

    msg = MIMEMultipart()
    msg["From"] = settings.smtp_user
    msg["To"] = to
    msg["Subject"] = subject
    msg.attach(MIMEText(full_body, "plain"))

    # Attach resume PDF if available
    if resume_path:
        resume_file = Path(resume_path)
        if resume_file.exists() and resume_file.suffix.lower() == ".pdf":
            with open(resume_file, "rb") as f:
                attachment = MIMEApplication(f.read(), _subtype="pdf")
                attachment.add_header(
                    "Content-Disposition", "attachment",
                    filename=f"Resume - {resume_file.stem}.pdf"
                )
                msg.attach(attachment)

    with smtplib.SMTP(settings.smtp_host, settings.smtp_port) as server:
        server.starttls()
        server.login(settings.smtp_user, settings.smtp_pass)
        server.send_message(msg)
